---

# set sshd
  - name: Check the parmeter is not defined
    fail:
      msg: "VAR_RH_sshd_config is not defined"
    when: VAR_RH_sshd_config is not defined

  - name: Check if the lower grade parameter is defined
    fail:
      msg: "Parameter VAR_RH_sshd_config.key or VAR_RH_sshd_config.value is not defined."
    with_items: "{{ VAR_RH_sshd_config }}"
    when: item.key is not defined or item.value is not defined

  - name: Check if the parameter is empty
    fail:
      msg: "Parameter VAR_RH_sshd_config.key is NULL."
    with_items: "{{ VAR_RH_sshd_config }}"
    when: item.key == "" or item.key == none or item.value == "" or item.value == none

  - name: install package
    yum:
      name: openssh-server
      state: present

  - name: start and enable service
    service:
      name: sshd
      state: started
      enabled: yes

  - name: delete the key_value
    lineinfile:
      dest: '/etc/ssh/sshd_config'
      state: absent
      regexp: '^\s*{{ item.key }}'
    with_items: "{{ VAR_RH_sshd_config }}"

  - name: set parameter
    lineinfile:
      dest: '/etc/ssh/sshd_config'
      state: present
      insertafter: '^\s*#\s*{{ item.key }}'
      line: "{{ item.key }} {{ {true: 'yes', false: 'no'}[item.value] | default(item.value) }}"
      create: yes
    with_items: "{{ VAR_RH_sshd_config }}"

  - name: sshd_restart
    service: >
      name=sshd
      state=restarted