---
#
# modify rsyslog.d
#

  - name: copy files to dest machine
    copy:
       src: '{{ item }}'
       dest: '/etc/rsyslog.d/{{ item }}'
       force: yes
       mode: 0644
       owner: root
       group: root
    with_items: "{{ VAR_RH_rsyslog_d_files }}"
    when: item is defined and not not item

