---
# not check `ANSIBLE0006` by ansible-lint
#modify nsswitch

  - name: clear nsswitch
    lineinfile:
      path: '/etc/nsswitch.conf'
      regexp: '^\s*hosts:'
      line: 'hosts:'
      state: present

  - name: modify nsswitch
    shell: sed -i 's/^hosts:.*/& {{ item.method }} {{item.actions | d() }}/g' /etc/nsswitch.conf
    with_items: "{{ VAR_RH_name_resolve_nsswitch }}"
    failed_when: item.method is not defined or item.method == '' or item.method == none
    tags:
      - skip_ansible_lint
