---
# not check `ANSIBLE0006` by ansible-lint

#modify hosts

  - name: set dns for ipv6 disabled
    shell: sed -r -i 's/^[^#]([0-9a-fA-F]{0,4}:){1,7}/#&/g' /etc/hosts
    when:
      - VAR_RH_name_resolve_ipv6_disabled is defined
      - VAR_RH_name_resolve_ipv6_disabled
    tags:
      - skip_ansible_lint

  - name: Hosts - register IPv4 name
    lineinfile:
      dest: '/etc/hosts'
      state: present
      regexp: '{{ item.ip }}\s*{{item.hostname}}'
      line: "{{ item.ip }}     {{ item.hostname }}"
    with_items: "{{ VAR_RH_name_resolve_hosts }}"
    failed_when: item.hostname == "" or item.hostname == none or item.ip == "" or item.ip ==none or item.ip is not defined or item.hostname is not defined

