---
# not check `ANSIBLE0006` by ansible-lint

  #post_check kdump_status
  - name: post_check kdump status
    raw: systemctl is-active kdump.service
    register: kdp_status
    ignore_errors: true
    changed_when: false
    failed_when: >
      ( kdp_status.stdout_lines.0 == "inactive" and VAR_RH_kdump.state == "started" ) or ( kdp_status.stdout_lines.0 == "active" and VAR_RH_kdump.state == "stopped")
    tags:
      - skip_ansible_lint

