---
# not check `ANSIBLE0006` by ansible-lint
# not check `COMPLIANCE020201` by ansible-lint
# Linux change the SystemRunlevel

  - name: Check if the parameter is defined
    fail:
      msg: "Parameter VAR_NEC_RH_runlevel is not defined."
    when: VAR_NEC_RH_runlevel is not defined

  - name: Check if the parameter is empty
    fail:
      msg: "Parameter VAR_NEC_RH_runlevel is NULL."
    when:
      - VAR_NEC_RH_runlevel is defined
      - VAR_NEC_RH_runlevel == "" or VAR_NEC_RH_runlevel is none

  - name: set tmp variable "runlevel_target"
    set_fact:
      runlevel_target: ["poweroff.target", "rescue.target", "multi-user.target", "graphical.target", "reboot.target"]

  - name: Check if the parameters are correct
    fail:
      msg: "The value of parameter VAR_NEC_RH_runlevel is incorrect."
    when: VAR_NEC_RH_runlevel  not in runlevel_target

  - name: get the current system runlevel
    command: "systemctl get-default"
    register: runlevel_state
    changed_when: runlevel_state != 0
    tags:
      - skip_ansible_lint
  - name: set the runlevel
    command: "systemctl set-default {{ VAR_NEC_RH_runlevel }}"
    when: runlevel_state.stdout != VAR_NEC_RH_runlevel
    tags:
      - skip_ansible_lint