---
# not check `COMPLIANCE020201` by ansible-lint
#/etc/default/grub
  - name: set variable RH_reboot_required
    set_fact:
      RH_reboot_required: "{{ RH_reboot_required | d(false) }}"

  - import_tasks: modify.yml
