---

# not check `ANSIBLE0016` by ansible-lint
#post check

 # check default gw
  - name: post_check default gw if(0)
    shell: ip route | grep 'default via {{item.item.gateway}} dev {{item.stdout_lines.0}}'
    register: gw_ret
    with_items: "{{ ret_if.results }}"
    when:
      - item.changed
      - (item.item.dest is defined and item.item.dest.split('/').0 == "") or item.item.dest is undefined
    failed_when: not gw_ret.stdout

  - name: post_check default gw if(1)
    shell: ip route | grep 'default via {{item.gateway}} dev {{item.interface}}'
    register: gw_ret
    with_items: "{{ VAR_RH_static_route }}"
    when:
      - item.interface is defined
      - (item.dest is defined and item.dest.split('/').0 == "") or item.dest is undefined
    failed_when: not gw_ret.stdout

  #post_check static route

  - name: post_check static route if(0) metric(0)
    shell: ip route | grep '{{item.item.dest}} via {{item.item.gateway}} dev {{ item.stdout_lines.0 }}'
    register: gw_ret
    with_items: "{{ ret_if.results }}"
    when:
      - item.changed
      - item.item.metric is undefined
      - item.item.dest is defined
      - item.item.dest.split('/').0 != "0.0.0.0"
    failed_when: not gw_ret.stdout

  - name: post_check static route if(0) metric(1)
    shell: ip route | grep '{{item.item.dest}} via {{item.item.gateway}} dev {{ item.stdout_lines.0 }} metric {{item.item.metric}}'
    register: gw_ret
    with_items: "{{ ret_if.results }}"
    when:
      - item.changed
      - item.item.metric is defined
      - item.item.dest is defined
      - item.item.dest.split('/').0 != "0.0.0.0"
    failed_when: not gw_ret.stdout

  - name: post_check static route if(1) metric(0)
    shell: ip route | grep '{{item.dest}} via {{item.gateway}} dev {{item.interface}}'
    register: gw_ret
    with_items: "{{ VAR_RH_static_route }}"
    when:
      - item.interface is defined
      - item.metric is undefined
      - item.dest is defined
      - item.dest.split('/').0 != "0.0.0.0"
    failed_when: not gw_ret.stdout

  - name: post_check static route if(1) metric(1)
    shell: ip route | grep '{{item.dest}} via {{item.gateway}} dev {{item.interface}} metric {{item.metric}}'
    register: gw_ret
    with_items: "{{ VAR_RH_static_route }}"
    when:
      - item.interface is defined
      - item.metric is defined
      - item.dest is defined
      - item.dest.split('/').0 != "0.0.0.0"
    failed_when: not gw_ret.stdout

